import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { Box, Skeleton } from "@mui/material";
import { FunctionComponent, useState, useEffect } from "react";
import DMBannerSection from "../components/DigitalMarketingBanner";
import Layout from "../components/Layout";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import FacebookPackages from "../components/FacebookPackages";

const DigitalMarketing:FunctionComponent = () => {
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    window.onload = (event) => {
      setLoading(!loading);
    };
  });
    return(
      <>
      <Head>
        <title>DCT Digital Marketing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/logo.svg" />
      </Head>
      {loading ? (
        <>
          <Skeleton variant="rectangular" width="100%" height={50} />

          <br />
          <Skeleton variant="rectangular" width="100%" height={400} />
          <br />
          <Skeleton variant="text" width="20%" height={50} />
          <br />
          <Skeleton variant="rectangular" width="250" height={250} />
        </>
      ) : (
      <Layout>
        <DMBannerSection />
        <FacebookPackages />
      </Layout>
    )}
    </>
    );
}

export const getStaticProps: GetStaticProps = async ({ locale }: any) => {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["landing"])),
    },
  };
};

export default DigitalMarketing;