import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { Box, Skeleton } from "@mui/material";
import { FunctionComponent, useState, useEffect } from "react";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import dynamic from "next/dynamic";
const DMBannerSection = dynamic(
  import("../components/DigitalMarketingBanner"),
  { ssr: false }
);
const PageLikeViewCard = dynamic(import("../components/PageLikeViewCard"), {
  ssr: false,
});
const Layout = dynamic(import("../components/Layout"), { ssr: false });
const FacebookPackages = dynamic(import("../components/FacebookPackages"), {
  ssr: false,
});
const ServiceSteps = dynamic(import("../components/ServiceSteps"), {
  ssr: false,
});

const DigitalMarketing: FunctionComponent = () => {
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    window.onload = (event) => {
      setLoading(!loading);
    };
  });
  return (
    <>
      <Head>
        <title>DCT Digital Marketing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/logo.svg" />
      </Head>
      <Layout>
        <DMBannerSection />
        <FacebookPackages />
        <PageLikeViewCard />
        <ServiceSteps />
      </Layout>
    </>
  );
};

export const getStaticProps: GetStaticProps = async ({ locale }: any) => {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["landing"])),
    },
  };
};

export default DigitalMarketing;