import Head from "next/head";
import { FunctionComponent, useState, useEffect } from "react";
import dynamic from "next/dynamic";
import { Box, Skeleton } from "@mui/material";

const Layout = dynamic(import("../components/Layout"), { ssr: false });
const MostSearchCards = dynamic(import("../components/MostSearchCards"), {
  ssr: false,
});
const BannerSection = dynamic(import("../components/BannerSection"), {
  ssr: false,
});
const OurServices = dynamic(import("../components/OurServices"), {
  ssr: false,
});
const DCTSection = dynamic(import("../components/DCTSection"), { ssr: false });
const AsxoxShopAppSection = dynamic(
  import("../components/AsxoxShopAppSection"),
  { ssr: false }
);
const SYRealEstateSection = dynamic(
  import("../components/SYRealEstateSection"),
  { ssr: false }
);
const EventLotterySection = dynamic(
  import("../components/EventLotterySection"),
  { ssr: false }
);
const DCTAppSection = dynamic(import("../components/DCTAppSection"), {
  ssr: false,
});

const Home: FunctionComponent = () => {
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    window.onload = (event) => {
      setLoading(!loading);
    };
  });
  return (
    <>
      <Head>
        <title>DCT Company</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/logo.svg" />
      </Head>
      {loading ? (
        <>
          <Skeleton variant="rectangular" width="100%" height={50} />

          <br />
          <Skeleton variant="rectangular" width="100%" height={400} />
          <br />
          <Skeleton variant="text" width="20%" height={50} />
          <br />
          <Skeleton variant="rectangular" width="250" height={250} />
        </>
      ) : (
        <Layout>
          <BannerSection />
          <MostSearchCards />
          <OurServices />
          <DCTSection />
          <AsxoxShopAppSection />
          <SYRealEstateSection />
          <EventLotterySection />
          <DCTAppSection />
        </Layout>
      )}
    </>
  );
};

export default Home;