import Head from "next/head";
import { FunctionComponent } from "react";
import dynamic from "next/dynamic";

const Layout = dynamic(import("../components/Layout"), { ssr: false });
const MostSearchCards = dynamic(import("../components/MostSearchCards"), {
  ssr: false,
});
const BannerSection = dynamic(import("../components/BannerSection"), {
  ssr: false,
});
const OurServices = dynamic(import("../components/OurServices"), {
  ssr: false,
});
const DCTSection = dynamic(import("../components/DCTSection"), { ssr: false });
const AsxoxShopAppSection = dynamic(
  import("../components/AsxoxShopAppSection"),
  { ssr: false }
);
const SYRealEstateSection = dynamic(
  import("../components/SYRealEstateSection"),
  { ssr: false }
);
const EventLotterySection = dynamic(
  import("../components/EventLotterySection"),
  { ssr: false }
);
const DCTAppSection = dynamic(import("../components/DCTAppSection"), {
  ssr: false,
});

const Home: FunctionComponent = () => {
  return (
    <>
      <Head>
        <title>DCT Company</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/logo.svg" />
      </Head>

      <Layout>
        <BannerSection />
        <MostSearchCards />
        <OurServices />
        <DCTSection />
        <AsxoxShopAppSection />
        <SYRealEstateSection />
        <EventLotterySection />
        <DCTAppSection />
      </Layout>
    </>
  );
};

export default Home;