import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { FunctionComponent } from "react";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import dynamic from "next/dynamic";
const SoftwareDevBanner = dynamic(
  import("../components/SoftwareDevBanner"),
  { ssr: false }
);
const Layout = dynamic(import("../components/Layout"), { ssr: false });
const ServicePackages = dynamic(import("../components/ServicePackages"), {
  ssr: false,
});

const DigitalMarketing: FunctionComponent = () => {
  return (
    <>
      <Head>
        <title>DCT - Software Development</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/logo.svg" />
      </Head>
      <Layout>
        <SoftwareDevBanner />
        <ServicePackages />
      </Layout>
    </>
  );
};

export const getStaticProps: GetStaticProps = async ({ locale }: any) => {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["landing"])),
    },
  };
};

export default DigitalMarketing;